# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 06:12
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=redactor.fields.RedactorField(blank=True, verbose_name='Text'),
        ),
    ]
