# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20151116_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='youtube_id',
            new_name='video_id',
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[(b'Google', b'Google'), (b'Facebook', b'Facebook')], default='Google', max_length=16),
            preserve_default=False,
        ),
    ]
