# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20160119_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[(b'Google', b'Google'), (b'Facebook', b'Facebook')], max_length=16),
        ),
    ]
